Update legendsock

diff --git a/legendsock b/legendsock
--- a/legendsock
+++ b/legendsock
@@ -9,10 +9,10 @@ if [ ! -d "/usr/local/legendsock" ]; then
 fi
 
 # 检查是否 CentOS
-if [ "`cat /etc/redhat-release 2>/dev/null| cut -d\  -f1`" != "CentOS" ]; then
-  echo "Error: The current system is not CentOS";
-  exit 1;
-fi
+#if [ "`cat /etc/redhat-release 2>/dev/null| cut -d\  -f1`" != "CentOS" ]; then
+#  echo "Error: The current system is not CentOS";
+#  exit 1;
+#fi
 
 legendsock_start()
 {
